id = "programming_language_tree_sitter"
version = "0.0.1"
schema_version = 1
authors = ["OkaniYoshiii"]
description = "Tree sitter for my new programming language"
name = "Programming language"
grammar = "programming-language"
path_suffixes = ["pl"]
line_comments = ["// "]
tab_size = 4
hard_tabs = false

[grammars.pl]
repository = "file://home/debian/projects/programming-language/tree-sitter"
rev = ""
