/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 135
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_i32 = 3,
  anon_sym_f32 = 4,
  anon_sym_string = 5,
  sym_identifier = 6,
  sym__string = 7,
  sym__int = 8,
  anon_sym_true = 9,
  anon_sym_false = 10,
  sym_fn_keyword = 11,
  sym_return_keyword = 12,
  sym_var_keyword = 13,
  sym_const_keyword = 14,
  sym_union_keyword = 15,
  sym_struct_keyword = 16,
  sym_package_keyword = 17,
  sym_if_keyword = 18,
  sym_greater_or_equal_than_operator = 19,
  sym_less_or_equal_than_operator = 20,
  sym_greater_than_operator = 21,
  sym_less_than_operator = 22,
  sym_equality_operator = 23,
  anon_sym_SPACE = 24,
  anon_sym_LPAREN = 25,
  anon_sym_RPAREN = 26,
  anon_sym_LBRACE2 = 27,
  anon_sym_EQ = 28,
  anon_sym_COMMA = 29,
  anon_sym_COMMA2 = 30,
  anon_sym_LF = 31,
  anon_sym_SEMI = 32,
  sym_source_file = 33,
  sym__definition = 34,
  sym__statement = 35,
  sym_block = 36,
  sym_type = 37,
  sym_expression = 38,
  sym__true = 39,
  sym__false = 40,
  sym__comparison_operator = 41,
  sym_function_definition = 42,
  sym_struct_definition = 43,
  sym_union_definition = 44,
  sym_package_definition = 45,
  sym_constant_expression = 46,
  sym__boolean_expression = 47,
  sym__comparison_expression = 48,
  sym__simple_expression = 49,
  sym_const_statement = 50,
  sym_var_statement = 51,
  sym_return_statement = 52,
  sym_if_statement = 53,
  sym_parameter = 54,
  sym_parameters = 55,
  sym_struct_field = 56,
  sym__terminator = 57,
  aux_sym_source_file_repeat1 = 58,
  aux_sym_block_repeat1 = 59,
  aux_sym_struct_definition_repeat1 = 60,
  aux_sym_parameters_repeat1 = 61,
  aux_sym_struct_field_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_i32] = "i32",
  [anon_sym_f32] = "f32",
  [anon_sym_string] = "string",
  [sym_identifier] = "identifier",
  [sym__string] = "_string",
  [sym__int] = "_int",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_fn_keyword] = "fn_keyword",
  [sym_return_keyword] = "return_keyword",
  [sym_var_keyword] = "var_keyword",
  [sym_const_keyword] = "const_keyword",
  [sym_union_keyword] = "union_keyword",
  [sym_struct_keyword] = "struct_keyword",
  [sym_package_keyword] = "package_keyword",
  [sym_if_keyword] = "if_keyword",
  [sym_greater_or_equal_than_operator] = "greater_or_equal_than_operator",
  [sym_less_or_equal_than_operator] = "less_or_equal_than_operator",
  [sym_greater_than_operator] = "greater_than_operator",
  [sym_less_than_operator] = "less_than_operator",
  [sym_equality_operator] = "equality_operator",
  [anon_sym_SPACE] = " ",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ") ",
  [anon_sym_LBRACE2] = " {",
  [anon_sym_EQ] = " = ",
  [anon_sym_COMMA] = ", ",
  [anon_sym_COMMA2] = ",",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__statement] = "_statement",
  [sym_block] = "block",
  [sym_type] = "type",
  [sym_expression] = "expression",
  [sym__true] = "_true",
  [sym__false] = "_false",
  [sym__comparison_operator] = "_comparison_operator",
  [sym_function_definition] = "function_definition",
  [sym_struct_definition] = "struct_definition",
  [sym_union_definition] = "union_definition",
  [sym_package_definition] = "package_definition",
  [sym_constant_expression] = "constant_expression",
  [sym__boolean_expression] = "_boolean_expression",
  [sym__comparison_expression] = "_comparison_expression",
  [sym__simple_expression] = "_simple_expression",
  [sym_const_statement] = "const_statement",
  [sym_var_statement] = "var_statement",
  [sym_return_statement] = "return_statement",
  [sym_if_statement] = "if_statement",
  [sym_parameter] = "parameter",
  [sym_parameters] = "parameters",
  [sym_struct_field] = "struct_field",
  [sym__terminator] = "_terminator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_struct_definition_repeat1] = "struct_definition_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_struct_field_repeat1] = "struct_field_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_string] = anon_sym_string,
  [sym_identifier] = sym_identifier,
  [sym__string] = sym__string,
  [sym__int] = sym__int,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_fn_keyword] = sym_fn_keyword,
  [sym_return_keyword] = sym_return_keyword,
  [sym_var_keyword] = sym_var_keyword,
  [sym_const_keyword] = sym_const_keyword,
  [sym_union_keyword] = sym_union_keyword,
  [sym_struct_keyword] = sym_struct_keyword,
  [sym_package_keyword] = sym_package_keyword,
  [sym_if_keyword] = sym_if_keyword,
  [sym_greater_or_equal_than_operator] = sym_greater_or_equal_than_operator,
  [sym_less_or_equal_than_operator] = sym_less_or_equal_than_operator,
  [sym_greater_than_operator] = sym_greater_than_operator,
  [sym_less_than_operator] = sym_less_than_operator,
  [sym_equality_operator] = sym_equality_operator,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE2] = anon_sym_LBRACE2,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COMMA2] = anon_sym_COMMA2,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__statement] = sym__statement,
  [sym_block] = sym_block,
  [sym_type] = sym_type,
  [sym_expression] = sym_expression,
  [sym__true] = sym__true,
  [sym__false] = sym__false,
  [sym__comparison_operator] = sym__comparison_operator,
  [sym_function_definition] = sym_function_definition,
  [sym_struct_definition] = sym_struct_definition,
  [sym_union_definition] = sym_union_definition,
  [sym_package_definition] = sym_package_definition,
  [sym_constant_expression] = sym_constant_expression,
  [sym__boolean_expression] = sym__boolean_expression,
  [sym__comparison_expression] = sym__comparison_expression,
  [sym__simple_expression] = sym__simple_expression,
  [sym_const_statement] = sym_const_statement,
  [sym_var_statement] = sym_var_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_parameter] = sym_parameter,
  [sym_parameters] = sym_parameters,
  [sym_struct_field] = sym_struct_field,
  [sym__terminator] = sym__terminator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_struct_definition_repeat1] = aux_sym_struct_definition_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_struct_field_repeat1] = aux_sym_struct_field_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__string] = {
    .visible = false,
    .named = true,
  },
  [sym__int] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_fn_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_return_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_var_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_const_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_union_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_package_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_if_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_greater_or_equal_than_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_less_or_equal_than_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_greater_than_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_less_than_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_equality_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__true] = {
    .visible = false,
    .named = true,
  },
  [sym__false] = {
    .visible = false,
    .named = true,
  },
  [sym__comparison_operator] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_union_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_package_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_constant_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__boolean_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__comparison_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_const_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_var_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym__terminator] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_field_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_condition = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 8,
  [10] = 7,
  [11] = 6,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 12,
  [16] = 13,
  [17] = 17,
  [18] = 18,
  [19] = 18,
  [20] = 18,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 22,
  [30] = 22,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 26,
  [42] = 25,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 28,
  [47] = 27,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 24,
  [56] = 26,
  [57] = 57,
  [58] = 58,
  [59] = 40,
  [60] = 39,
  [61] = 61,
  [62] = 31,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 38,
  [68] = 37,
  [69] = 36,
  [70] = 70,
  [71] = 26,
  [72] = 72,
  [73] = 33,
  [74] = 35,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 83,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 86,
  [91] = 24,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 38,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 82,
  [104] = 104,
  [105] = 31,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 82,
  [113] = 104,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 120,
  [122] = 115,
  [123] = 102,
  [124] = 101,
  [125] = 101,
  [126] = 97,
  [127] = 98,
  [128] = 128,
  [129] = 129,
  [130] = 114,
  [131] = 128,
  [132] = 129,
  [133] = 129,
  [134] = 134,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        ' ', 2,
        '"', 10,
        '(', 108,
        ')', 3,
        ',', 113,
        ';', 116,
        '<', 104,
        '=', 17,
        '>', 103,
        'c', 39,
        'f', 15,
        'i', 16,
        'p', 18,
        'r', 26,
        's', 50,
        't', 41,
        'u', 34,
        'v', 20,
        '{', 58,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 2,
        '"', 10,
        '(', 108,
        ')', 3,
        ',', 113,
        ';', 116,
        '<', 104,
        '=', 17,
        '>', 103,
        'c', 39,
        'f', 15,
        'i', 16,
        'p', 18,
        'r', 26,
        's', 50,
        't', 41,
        'u', 34,
        'v', 20,
        '{', 58,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        ' ', 2,
        '"', 10,
        '(', 108,
        ')', 3,
        ',', 113,
        ';', 116,
        '<', 104,
        '=', 4,
        '>', 103,
        'c', 39,
        'f', 15,
        'i', 16,
        'p', 18,
        'r', 26,
        's', 50,
        't', 41,
        'u', 34,
        'v', 20,
        '{', 58,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(109);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(111);
      if (lookahead == '=') ADVANCE(105);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(112);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(6);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == 'f') ADVANCE(63);
      if (lookahead == 't') ADVANCE(73);
      if (lookahead == '{') ADVANCE(110);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(6);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == 'f') ADVANCE(63);
      if (lookahead == 't') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        ' ', 107,
        'c', 39,
        'f', 14,
        'i', 16,
        'r', 26,
        's', 52,
        'v', 20,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(8);
      END_STATE();
    case 9:
      ADVANCE_MAP(
        '"', 10,
        ')', 3,
        ',', 5,
        'c', 72,
        'f', 63,
        'i', 68,
        'r', 65,
        't', 73,
        'v', 64,
        '{', 58,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == ')') ADVANCE(3);
      if (lookahead == '}') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 12:
      if (lookahead == '2') ADVANCE(61);
      END_STATE();
    case 13:
      if (lookahead == '2') ADVANCE(60);
      END_STATE();
    case 14:
      if (lookahead == '3') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == '3') ADVANCE(12);
      if (lookahead == 'a') ADVANCE(33);
      if (lookahead == 'n') ADVANCE(89);
      END_STATE();
    case 16:
      if (lookahead == '3') ADVANCE(13);
      if (lookahead == 'f') ADVANCE(99);
      END_STATE();
    case 17:
      if (lookahead == '=') ADVANCE(105);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(49);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 27:
      if (lookahead == 'g') ADVANCE(62);
      END_STATE();
    case 28:
      if (lookahead == 'g') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(38);
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 'k') ADVANCE(19);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(96);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(92);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 47:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(97);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 53:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 54:
      if (lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 55:
      if (eof) ADVANCE(57);
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == ';') ADVANCE(116);
      if (lookahead == 'f') ADVANCE(63);
      if (lookahead == 't') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 56:
      if (eof) ADVANCE(57);
      if (lookahead == '\n') ADVANCE(115);
      if (lookahead == ' ') ADVANCE(106);
      if (lookahead == ';') ADVANCE(116);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(88);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(100);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(77);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(91);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(80);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(95);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(75);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym__string);
      if (lookahead == '"') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym__int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_true);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_false);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_fn_keyword);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_return_keyword);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_return_keyword);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_var_keyword);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_var_keyword);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_const_keyword);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_const_keyword);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_union_keyword);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_struct_keyword);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_package_keyword);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_if_keyword);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_if_keyword);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_greater_or_equal_than_operator);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_less_or_equal_than_operator);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_greater_than_operator);
      if (lookahead == '=') ADVANCE(101);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_less_than_operator);
      if (lookahead == '=') ADVANCE(102);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_equality_operator);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\n') ADVANCE(115);
      if (lookahead == ' ') ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_LBRACE2);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_COMMA2);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(115);
      if (lookahead == ' ') ADVANCE(106);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 55},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 56},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 56},
  [47] = {.lex_state = 56},
  [48] = {.lex_state = 11},
  [49] = {.lex_state = 11},
  [50] = {.lex_state = 55},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 55},
  [55] = {.lex_state = 56},
  [56] = {.lex_state = 56},
  [57] = {.lex_state = 55},
  [58] = {.lex_state = 55},
  [59] = {.lex_state = 55},
  [60] = {.lex_state = 55},
  [61] = {.lex_state = 55},
  [62] = {.lex_state = 55},
  [63] = {.lex_state = 55},
  [64] = {.lex_state = 55},
  [65] = {.lex_state = 55},
  [66] = {.lex_state = 11},
  [67] = {.lex_state = 55},
  [68] = {.lex_state = 55},
  [69] = {.lex_state = 55},
  [70] = {.lex_state = 55},
  [71] = {.lex_state = 55},
  [72] = {.lex_state = 11},
  [73] = {.lex_state = 55},
  [74] = {.lex_state = 55},
  [75] = {.lex_state = 55},
  [76] = {.lex_state = 9},
  [77] = {.lex_state = 9},
  [78] = {.lex_state = 9},
  [79] = {.lex_state = 11},
  [80] = {.lex_state = 11},
  [81] = {.lex_state = 9},
  [82] = {.lex_state = 9},
  [83] = {.lex_state = 9},
  [84] = {.lex_state = 9},
  [85] = {.lex_state = 9},
  [86] = {.lex_state = 11},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 8},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 11},
  [91] = {.lex_state = 8},
  [92] = {.lex_state = 11},
  [93] = {.lex_state = 11},
  [94] = {.lex_state = 11},
  [95] = {.lex_state = 8},
  [96] = {.lex_state = 11},
  [97] = {.lex_state = 8},
  [98] = {.lex_state = 8},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 7},
  [101] = {.lex_state = 8},
  [102] = {.lex_state = 8},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 8},
  [105] = {.lex_state = 8},
  [106] = {.lex_state = 8},
  [107] = {.lex_state = 8},
  [108] = {.lex_state = 8},
  [109] = {.lex_state = 8},
  [110] = {.lex_state = 7},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 8},
  [113] = {.lex_state = 8},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 8},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 11},
  [119] = {.lex_state = 8},
  [120] = {.lex_state = 11},
  [121] = {.lex_state = 11},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 8},
  [124] = {.lex_state = 8},
  [125] = {.lex_state = 8},
  [126] = {.lex_state = 8},
  [127] = {.lex_state = 8},
  [128] = {.lex_state = 8},
  [129] = {.lex_state = 8},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 8},
  [132] = {.lex_state = 8},
  [133] = {.lex_state = 8},
  [134] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [sym__string] = ACTIONS(1),
    [sym__int] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_fn_keyword] = ACTIONS(1),
    [sym_return_keyword] = ACTIONS(1),
    [sym_var_keyword] = ACTIONS(1),
    [sym_const_keyword] = ACTIONS(1),
    [sym_union_keyword] = ACTIONS(1),
    [sym_struct_keyword] = ACTIONS(1),
    [sym_package_keyword] = ACTIONS(1),
    [sym_if_keyword] = ACTIONS(1),
    [sym_greater_or_equal_than_operator] = ACTIONS(1),
    [sym_less_or_equal_than_operator] = ACTIONS(1),
    [sym_greater_than_operator] = ACTIONS(1),
    [sym_less_than_operator] = ACTIONS(1),
    [sym_equality_operator] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE2] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA2] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(87),
    [sym__definition] = STATE(50),
    [sym__statement] = STATE(50),
    [sym_function_definition] = STATE(50),
    [sym_struct_definition] = STATE(50),
    [sym_union_definition] = STATE(50),
    [sym_package_definition] = STATE(50),
    [sym_const_statement] = STATE(50),
    [sym_var_statement] = STATE(50),
    [sym_return_statement] = STATE(50),
    [sym_if_statement] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_fn_keyword] = ACTIONS(5),
    [sym_return_keyword] = ACTIONS(7),
    [sym_var_keyword] = ACTIONS(9),
    [sym_const_keyword] = ACTIONS(11),
    [sym_union_keyword] = ACTIONS(13),
    [sym_struct_keyword] = ACTIONS(15),
    [sym_package_keyword] = ACTIONS(17),
    [sym_if_keyword] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      sym_fn_keyword,
    ACTIONS(7), 1,
      sym_return_keyword,
    ACTIONS(9), 1,
      sym_var_keyword,
    ACTIONS(11), 1,
      sym_const_keyword,
    ACTIONS(13), 1,
      sym_union_keyword,
    ACTIONS(15), 1,
      sym_struct_keyword,
    ACTIONS(17), 1,
      sym_package_keyword,
    ACTIONS(19), 1,
      sym_if_keyword,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(54), 10,
      sym__definition,
      sym__statement,
      sym_function_definition,
      sym_struct_definition,
      sym_union_definition,
      sym_package_definition,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
  [43] = 11,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_fn_keyword,
    ACTIONS(28), 1,
      sym_return_keyword,
    ACTIONS(31), 1,
      sym_var_keyword,
    ACTIONS(34), 1,
      sym_const_keyword,
    ACTIONS(37), 1,
      sym_union_keyword,
    ACTIONS(40), 1,
      sym_struct_keyword,
    ACTIONS(43), 1,
      sym_package_keyword,
    ACTIONS(46), 1,
      sym_if_keyword,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(70), 10,
      sym__definition,
      sym__statement,
      sym_function_definition,
      sym_struct_definition,
      sym_union_definition,
      sym_package_definition,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
  [86] = 10,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(24), 1,
      sym_constant_expression,
    STATE(35), 1,
      sym_expression,
    STATE(133), 1,
      sym__simple_expression,
    ACTIONS(53), 2,
      sym__string,
      sym__int,
    ACTIONS(55), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym__true,
      sym__false,
    STATE(38), 2,
      sym__boolean_expression,
      sym__comparison_expression,
    ACTIONS(57), 4,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [124] = 10,
    ACTIONS(57), 1,
      anon_sym_SEMI,
    ACTIONS(59), 1,
      sym_identifier,
    STATE(55), 1,
      sym_constant_expression,
    STATE(74), 1,
      sym_expression,
    STATE(129), 1,
      sym__simple_expression,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(61), 2,
      sym__string,
      sym__int,
    ACTIONS(63), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(42), 2,
      sym__true,
      sym__false,
    STATE(67), 2,
      sym__boolean_expression,
      sym__comparison_expression,
  [160] = 8,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(91), 1,
      sym_constant_expression,
    STATE(102), 1,
      sym_expression,
    STATE(132), 1,
      sym__simple_expression,
    ACTIONS(53), 2,
      sym__string,
      sym__int,
    ACTIONS(55), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym__true,
      sym__false,
    STATE(95), 2,
      sym__boolean_expression,
      sym__comparison_expression,
  [189] = 8,
    ACTIONS(67), 1,
      sym_identifier,
    STATE(47), 1,
      sym_constant_expression,
    STATE(73), 1,
      sym_expression,
    STATE(129), 1,
      sym__simple_expression,
    ACTIONS(63), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(69), 2,
      sym__string,
      sym__int,
    STATE(42), 2,
      sym__true,
      sym__false,
    STATE(67), 2,
      sym__boolean_expression,
      sym__comparison_expression,
  [218] = 8,
    ACTIONS(71), 1,
      sym_identifier,
    STATE(46), 1,
      sym_constant_expression,
    STATE(69), 1,
      sym_expression,
    STATE(129), 1,
      sym__simple_expression,
    ACTIONS(63), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(69), 2,
      sym__string,
      sym__int,
    STATE(42), 2,
      sym__true,
      sym__false,
    STATE(67), 2,
      sym__boolean_expression,
      sym__comparison_expression,
  [247] = 8,
    ACTIONS(73), 1,
      sym_identifier,
    STATE(28), 1,
      sym_constant_expression,
    STATE(36), 1,
      sym_expression,
    STATE(133), 1,
      sym__simple_expression,
    ACTIONS(53), 2,
      sym__string,
      sym__int,
    ACTIONS(55), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym__true,
      sym__false,
    STATE(38), 2,
      sym__boolean_expression,
      sym__comparison_expression,
  [276] = 8,
    ACTIONS(75), 1,
      sym_identifier,
    STATE(27), 1,
      sym_constant_expression,
    STATE(33), 1,
      sym_expression,
    STATE(133), 1,
      sym__simple_expression,
    ACTIONS(53), 2,
      sym__string,
      sym__int,
    ACTIONS(55), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym__true,
      sym__false,
    STATE(38), 2,
      sym__boolean_expression,
      sym__comparison_expression,
  [305] = 8,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(91), 1,
      sym_constant_expression,
    STATE(123), 1,
      sym_expression,
    STATE(132), 1,
      sym__simple_expression,
    ACTIONS(53), 2,
      sym__string,
      sym__int,
    ACTIONS(55), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym__true,
      sym__false,
    STATE(95), 2,
      sym__boolean_expression,
      sym__comparison_expression,
  [334] = 6,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 1,
      sym_return_keyword,
    ACTIONS(81), 1,
      sym_var_keyword,
    ACTIONS(83), 1,
      sym_const_keyword,
    ACTIONS(85), 1,
      sym_if_keyword,
    STATE(13), 6,
      sym__statement,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
      aux_sym_block_repeat1,
  [358] = 6,
    ACTIONS(79), 1,
      sym_return_keyword,
    ACTIONS(81), 1,
      sym_var_keyword,
    ACTIONS(83), 1,
      sym_const_keyword,
    ACTIONS(85), 1,
      sym_if_keyword,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    STATE(14), 6,
      sym__statement,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
      aux_sym_block_repeat1,
  [382] = 6,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    ACTIONS(91), 1,
      sym_return_keyword,
    ACTIONS(94), 1,
      sym_var_keyword,
    ACTIONS(97), 1,
      sym_const_keyword,
    ACTIONS(100), 1,
      sym_if_keyword,
    STATE(14), 6,
      sym__statement,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
      aux_sym_block_repeat1,
  [406] = 6,
    ACTIONS(79), 1,
      sym_return_keyword,
    ACTIONS(81), 1,
      sym_var_keyword,
    ACTIONS(83), 1,
      sym_const_keyword,
    ACTIONS(85), 1,
      sym_if_keyword,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(16), 6,
      sym__statement,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
      aux_sym_block_repeat1,
  [430] = 6,
    ACTIONS(79), 1,
      sym_return_keyword,
    ACTIONS(81), 1,
      sym_var_keyword,
    ACTIONS(83), 1,
      sym_const_keyword,
    ACTIONS(85), 1,
      sym_if_keyword,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(14), 6,
      sym__statement,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
      aux_sym_block_repeat1,
  [454] = 1,
    ACTIONS(23), 9,
      ts_builtin_sym_end,
      sym_fn_keyword,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_union_keyword,
      sym_struct_keyword,
      sym_package_keyword,
      sym_if_keyword,
  [466] = 5,
    ACTIONS(107), 1,
      sym_identifier,
    ACTIONS(109), 2,
      sym__string,
      sym__int,
    ACTIONS(111), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(62), 2,
      sym_constant_expression,
      sym__simple_expression,
    STATE(71), 2,
      sym__true,
      sym__false,
  [486] = 5,
    ACTIONS(113), 1,
      sym_identifier,
    ACTIONS(53), 2,
      sym__string,
      sym__int,
    ACTIONS(115), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 2,
      sym__true,
      sym__false,
    STATE(105), 2,
      sym_constant_expression,
      sym__simple_expression,
  [506] = 5,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(119), 2,
      sym__string,
      sym__int,
    ACTIONS(121), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(31), 2,
      sym_constant_expression,
      sym__simple_expression,
    STATE(41), 2,
      sym__true,
      sym__false,
  [526] = 4,
    ACTIONS(125), 1,
      anon_sym_SPACE,
    STATE(23), 1,
      aux_sym_struct_field_repeat1,
    STATE(89), 1,
      sym_type,
    ACTIONS(123), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [541] = 3,
    STATE(101), 1,
      sym__comparison_operator,
    ACTIONS(129), 2,
      sym_greater_than_operator,
      sym_less_than_operator,
    ACTIONS(127), 3,
      sym_greater_or_equal_than_operator,
      sym_less_or_equal_than_operator,
      sym_equality_operator,
  [554] = 4,
    ACTIONS(131), 1,
      anon_sym_SPACE,
    STATE(34), 1,
      aux_sym_struct_field_repeat1,
    STATE(117), 1,
      sym_type,
    ACTIONS(123), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [569] = 2,
    ACTIONS(135), 1,
      anon_sym_SPACE,
    ACTIONS(133), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [580] = 2,
    ACTIONS(139), 1,
      anon_sym_SPACE,
    ACTIONS(137), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [591] = 2,
    ACTIONS(139), 1,
      anon_sym_SPACE,
    ACTIONS(137), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [602] = 2,
    ACTIONS(135), 1,
      anon_sym_SPACE,
    ACTIONS(133), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [613] = 2,
    ACTIONS(135), 1,
      anon_sym_SPACE,
    ACTIONS(133), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [624] = 3,
    STATE(124), 1,
      sym__comparison_operator,
    ACTIONS(143), 2,
      sym_greater_than_operator,
      sym_less_than_operator,
    ACTIONS(141), 3,
      sym_greater_or_equal_than_operator,
      sym_less_or_equal_than_operator,
      sym_equality_operator,
  [637] = 3,
    STATE(125), 1,
      sym__comparison_operator,
    ACTIONS(147), 2,
      sym_greater_than_operator,
      sym_less_than_operator,
    ACTIONS(145), 3,
      sym_greater_or_equal_than_operator,
      sym_less_or_equal_than_operator,
      sym_equality_operator,
  [650] = 1,
    ACTIONS(149), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [658] = 5,
    ACTIONS(151), 1,
      sym_identifier,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      aux_sym_parameters_repeat1,
    STATE(81), 1,
      sym_parameter,
    STATE(99), 1,
      sym_parameters,
  [674] = 1,
    ACTIONS(155), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [682] = 3,
    ACTIONS(159), 1,
      anon_sym_SPACE,
    STATE(34), 1,
      aux_sym_struct_field_repeat1,
    ACTIONS(157), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [694] = 1,
    ACTIONS(162), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [702] = 1,
    ACTIONS(164), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [710] = 1,
    ACTIONS(166), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [718] = 1,
    ACTIONS(168), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [726] = 1,
    ACTIONS(170), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [734] = 1,
    ACTIONS(172), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [742] = 1,
    ACTIONS(139), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [750] = 2,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 3,
      anon_sym_SPACE,
      anon_sym_LF,
      anon_sym_SEMI,
  [759] = 3,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(48), 2,
      sym_struct_field,
      aux_sym_struct_definition_repeat1,
  [770] = 3,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    STATE(49), 2,
      sym_struct_field,
      aux_sym_struct_definition_repeat1,
  [781] = 2,
    STATE(116), 1,
      sym_type,
    ACTIONS(180), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [790] = 3,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 1,
      anon_sym_SPACE,
    ACTIONS(133), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [801] = 3,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 1,
      anon_sym_SPACE,
    ACTIONS(133), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [812] = 3,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(53), 2,
      sym_struct_field,
      aux_sym_struct_definition_repeat1,
  [823] = 3,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
    STATE(53), 2,
      sym_struct_field,
      aux_sym_struct_definition_repeat1,
  [834] = 4,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(188), 1,
      anon_sym_LF,
    ACTIONS(190), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      sym__terminator,
  [847] = 2,
    STATE(76), 1,
      sym_type,
    ACTIONS(192), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [856] = 2,
    STATE(109), 1,
      sym_type,
    ACTIONS(180), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [865] = 3,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    ACTIONS(196), 1,
      sym_identifier,
    STATE(53), 2,
      sym_struct_field,
      aux_sym_struct_definition_repeat1,
  [876] = 4,
    ACTIONS(188), 1,
      anon_sym_LF,
    ACTIONS(190), 1,
      anon_sym_SEMI,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      sym__terminator,
  [889] = 3,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 1,
      anon_sym_SPACE,
    ACTIONS(133), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [900] = 2,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 3,
      anon_sym_SPACE,
      anon_sym_LF,
      anon_sym_SEMI,
  [909] = 2,
    ACTIONS(203), 1,
      anon_sym_SEMI,
    ACTIONS(201), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [917] = 2,
    ACTIONS(207), 1,
      anon_sym_SEMI,
    ACTIONS(205), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [925] = 2,
    ACTIONS(209), 1,
      anon_sym_SEMI,
    ACTIONS(172), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [933] = 2,
    ACTIONS(211), 1,
      anon_sym_SEMI,
    ACTIONS(170), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [941] = 2,
    ACTIONS(215), 1,
      anon_sym_SEMI,
    ACTIONS(213), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [949] = 2,
    ACTIONS(217), 1,
      anon_sym_SEMI,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [957] = 2,
    ACTIONS(221), 1,
      anon_sym_SEMI,
    ACTIONS(219), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [965] = 2,
    ACTIONS(225), 1,
      anon_sym_SEMI,
    ACTIONS(223), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [973] = 2,
    ACTIONS(229), 1,
      anon_sym_SEMI,
    ACTIONS(227), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [981] = 3,
    ACTIONS(151), 1,
      sym_identifier,
    STATE(72), 1,
      aux_sym_parameters_repeat1,
    STATE(84), 1,
      sym_parameter,
  [991] = 2,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    ACTIONS(168), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [999] = 2,
    ACTIONS(231), 1,
      anon_sym_SEMI,
    ACTIONS(166), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1007] = 2,
    ACTIONS(233), 1,
      anon_sym_SEMI,
    ACTIONS(164), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1015] = 3,
    ACTIONS(188), 1,
      anon_sym_LF,
    ACTIONS(190), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      sym__terminator,
  [1025] = 2,
    ACTIONS(137), 1,
      anon_sym_SEMI,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1033] = 3,
    ACTIONS(235), 1,
      sym_identifier,
    STATE(72), 1,
      aux_sym_parameters_repeat1,
    STATE(134), 1,
      sym_parameter,
  [1043] = 2,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1051] = 2,
    ACTIONS(240), 1,
      anon_sym_SEMI,
    ACTIONS(162), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1059] = 2,
    ACTIONS(244), 1,
      anon_sym_SEMI,
    ACTIONS(242), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [1067] = 1,
    ACTIONS(246), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1072] = 2,
    ACTIONS(248), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_block,
  [1079] = 2,
    ACTIONS(248), 1,
      anon_sym_LBRACE,
    STATE(63), 1,
      sym_block,
  [1086] = 1,
    ACTIONS(250), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1091] = 1,
    ACTIONS(252), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1096] = 2,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
    ACTIONS(256), 1,
      anon_sym_COMMA,
  [1103] = 1,
    ACTIONS(258), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1108] = 2,
    ACTIONS(260), 1,
      anon_sym_LBRACE,
    STATE(37), 1,
      sym_block,
  [1115] = 2,
    ACTIONS(256), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
  [1122] = 2,
    ACTIONS(248), 1,
      anon_sym_LBRACE,
    STATE(68), 1,
      sym_block,
  [1129] = 1,
    ACTIONS(264), 1,
      sym_identifier,
  [1133] = 1,
    ACTIONS(266), 1,
      ts_builtin_sym_end,
  [1137] = 1,
    ACTIONS(268), 1,
      anon_sym_SPACE,
  [1141] = 1,
    ACTIONS(270), 1,
      anon_sym_COMMA2,
  [1145] = 1,
    ACTIONS(272), 1,
      sym_identifier,
  [1149] = 1,
    ACTIONS(168), 1,
      anon_sym_SPACE,
  [1153] = 1,
    ACTIONS(274), 1,
      sym_identifier,
  [1157] = 1,
    ACTIONS(276), 1,
      sym_identifier,
  [1161] = 1,
    ACTIONS(278), 1,
      sym_identifier,
  [1165] = 1,
    ACTIONS(168), 1,
      anon_sym_SPACE,
  [1169] = 1,
    ACTIONS(280), 1,
      sym_identifier,
  [1173] = 1,
    ACTIONS(282), 1,
      anon_sym_SPACE,
  [1177] = 1,
    ACTIONS(284), 1,
      anon_sym_SPACE,
  [1181] = 1,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
  [1185] = 1,
    ACTIONS(288), 1,
      anon_sym_LBRACE2,
  [1189] = 1,
    ACTIONS(290), 1,
      anon_sym_SPACE,
  [1193] = 1,
    ACTIONS(292), 1,
      anon_sym_SPACE,
  [1197] = 1,
    ACTIONS(258), 1,
      anon_sym_COMMA2,
  [1201] = 1,
    ACTIONS(294), 1,
      anon_sym_SPACE,
  [1205] = 1,
    ACTIONS(149), 1,
      anon_sym_SPACE,
  [1209] = 1,
    ACTIONS(296), 1,
      anon_sym_SPACE,
  [1213] = 1,
    ACTIONS(298), 1,
      anon_sym_SPACE,
  [1217] = 1,
    ACTIONS(300), 1,
      anon_sym_SPACE,
  [1221] = 1,
    ACTIONS(302), 1,
      anon_sym_SPACE,
  [1225] = 1,
    ACTIONS(304), 1,
      anon_sym_LBRACE2,
  [1229] = 1,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
  [1233] = 1,
    ACTIONS(258), 1,
      anon_sym_SPACE,
  [1237] = 1,
    ACTIONS(308), 1,
      anon_sym_SPACE,
  [1241] = 1,
    ACTIONS(310), 1,
      anon_sym_EQ,
  [1245] = 1,
    ACTIONS(312), 1,
      anon_sym_EQ,
  [1249] = 1,
    ACTIONS(314), 1,
      anon_sym_SPACE,
  [1253] = 1,
    ACTIONS(316), 1,
      anon_sym_COMMA2,
  [1257] = 1,
    ACTIONS(318), 1,
      sym_identifier,
  [1261] = 1,
    ACTIONS(320), 1,
      anon_sym_SPACE,
  [1265] = 1,
    ACTIONS(322), 1,
      sym_identifier,
  [1269] = 1,
    ACTIONS(324), 1,
      sym_identifier,
  [1273] = 1,
    ACTIONS(326), 1,
      anon_sym_EQ,
  [1277] = 1,
    ACTIONS(328), 1,
      anon_sym_SPACE,
  [1281] = 1,
    ACTIONS(330), 1,
      anon_sym_SPACE,
  [1285] = 1,
    ACTIONS(332), 1,
      anon_sym_SPACE,
  [1289] = 1,
    ACTIONS(334), 1,
      anon_sym_SPACE,
  [1293] = 1,
    ACTIONS(336), 1,
      anon_sym_SPACE,
  [1297] = 1,
    ACTIONS(338), 1,
      anon_sym_SPACE,
  [1301] = 1,
    ACTIONS(340), 1,
      anon_sym_SPACE,
  [1305] = 1,
    ACTIONS(342), 1,
      anon_sym_EQ,
  [1309] = 1,
    ACTIONS(344), 1,
      anon_sym_SPACE,
  [1313] = 1,
    ACTIONS(346), 1,
      anon_sym_SPACE,
  [1317] = 1,
    ACTIONS(348), 1,
      anon_sym_SPACE,
  [1321] = 1,
    ACTIONS(256), 1,
      anon_sym_COMMA,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 124,
  [SMALL_STATE(6)] = 160,
  [SMALL_STATE(7)] = 189,
  [SMALL_STATE(8)] = 218,
  [SMALL_STATE(9)] = 247,
  [SMALL_STATE(10)] = 276,
  [SMALL_STATE(11)] = 305,
  [SMALL_STATE(12)] = 334,
  [SMALL_STATE(13)] = 358,
  [SMALL_STATE(14)] = 382,
  [SMALL_STATE(15)] = 406,
  [SMALL_STATE(16)] = 430,
  [SMALL_STATE(17)] = 454,
  [SMALL_STATE(18)] = 466,
  [SMALL_STATE(19)] = 486,
  [SMALL_STATE(20)] = 506,
  [SMALL_STATE(21)] = 526,
  [SMALL_STATE(22)] = 541,
  [SMALL_STATE(23)] = 554,
  [SMALL_STATE(24)] = 569,
  [SMALL_STATE(25)] = 580,
  [SMALL_STATE(26)] = 591,
  [SMALL_STATE(27)] = 602,
  [SMALL_STATE(28)] = 613,
  [SMALL_STATE(29)] = 624,
  [SMALL_STATE(30)] = 637,
  [SMALL_STATE(31)] = 650,
  [SMALL_STATE(32)] = 658,
  [SMALL_STATE(33)] = 674,
  [SMALL_STATE(34)] = 682,
  [SMALL_STATE(35)] = 694,
  [SMALL_STATE(36)] = 702,
  [SMALL_STATE(37)] = 710,
  [SMALL_STATE(38)] = 718,
  [SMALL_STATE(39)] = 726,
  [SMALL_STATE(40)] = 734,
  [SMALL_STATE(41)] = 742,
  [SMALL_STATE(42)] = 750,
  [SMALL_STATE(43)] = 759,
  [SMALL_STATE(44)] = 770,
  [SMALL_STATE(45)] = 781,
  [SMALL_STATE(46)] = 790,
  [SMALL_STATE(47)] = 801,
  [SMALL_STATE(48)] = 812,
  [SMALL_STATE(49)] = 823,
  [SMALL_STATE(50)] = 834,
  [SMALL_STATE(51)] = 847,
  [SMALL_STATE(52)] = 856,
  [SMALL_STATE(53)] = 865,
  [SMALL_STATE(54)] = 876,
  [SMALL_STATE(55)] = 889,
  [SMALL_STATE(56)] = 900,
  [SMALL_STATE(57)] = 909,
  [SMALL_STATE(58)] = 917,
  [SMALL_STATE(59)] = 925,
  [SMALL_STATE(60)] = 933,
  [SMALL_STATE(61)] = 941,
  [SMALL_STATE(62)] = 949,
  [SMALL_STATE(63)] = 957,
  [SMALL_STATE(64)] = 965,
  [SMALL_STATE(65)] = 973,
  [SMALL_STATE(66)] = 981,
  [SMALL_STATE(67)] = 991,
  [SMALL_STATE(68)] = 999,
  [SMALL_STATE(69)] = 1007,
  [SMALL_STATE(70)] = 1015,
  [SMALL_STATE(71)] = 1025,
  [SMALL_STATE(72)] = 1033,
  [SMALL_STATE(73)] = 1043,
  [SMALL_STATE(74)] = 1051,
  [SMALL_STATE(75)] = 1059,
  [SMALL_STATE(76)] = 1067,
  [SMALL_STATE(77)] = 1072,
  [SMALL_STATE(78)] = 1079,
  [SMALL_STATE(79)] = 1086,
  [SMALL_STATE(80)] = 1091,
  [SMALL_STATE(81)] = 1096,
  [SMALL_STATE(82)] = 1103,
  [SMALL_STATE(83)] = 1108,
  [SMALL_STATE(84)] = 1115,
  [SMALL_STATE(85)] = 1122,
  [SMALL_STATE(86)] = 1129,
  [SMALL_STATE(87)] = 1133,
  [SMALL_STATE(88)] = 1137,
  [SMALL_STATE(89)] = 1141,
  [SMALL_STATE(90)] = 1145,
  [SMALL_STATE(91)] = 1149,
  [SMALL_STATE(92)] = 1153,
  [SMALL_STATE(93)] = 1157,
  [SMALL_STATE(94)] = 1161,
  [SMALL_STATE(95)] = 1165,
  [SMALL_STATE(96)] = 1169,
  [SMALL_STATE(97)] = 1173,
  [SMALL_STATE(98)] = 1177,
  [SMALL_STATE(99)] = 1181,
  [SMALL_STATE(100)] = 1185,
  [SMALL_STATE(101)] = 1189,
  [SMALL_STATE(102)] = 1193,
  [SMALL_STATE(103)] = 1197,
  [SMALL_STATE(104)] = 1201,
  [SMALL_STATE(105)] = 1205,
  [SMALL_STATE(106)] = 1209,
  [SMALL_STATE(107)] = 1213,
  [SMALL_STATE(108)] = 1217,
  [SMALL_STATE(109)] = 1221,
  [SMALL_STATE(110)] = 1225,
  [SMALL_STATE(111)] = 1229,
  [SMALL_STATE(112)] = 1233,
  [SMALL_STATE(113)] = 1237,
  [SMALL_STATE(114)] = 1241,
  [SMALL_STATE(115)] = 1245,
  [SMALL_STATE(116)] = 1249,
  [SMALL_STATE(117)] = 1253,
  [SMALL_STATE(118)] = 1257,
  [SMALL_STATE(119)] = 1261,
  [SMALL_STATE(120)] = 1265,
  [SMALL_STATE(121)] = 1269,
  [SMALL_STATE(122)] = 1273,
  [SMALL_STATE(123)] = 1277,
  [SMALL_STATE(124)] = 1281,
  [SMALL_STATE(125)] = 1285,
  [SMALL_STATE(126)] = 1289,
  [SMALL_STATE(127)] = 1293,
  [SMALL_STATE(128)] = 1297,
  [SMALL_STATE(129)] = 1301,
  [SMALL_STATE(130)] = 1305,
  [SMALL_STATE(131)] = 1309,
  [SMALL_STATE(132)] = 1313,
  [SMALL_STATE(133)] = 1317,
  [SMALL_STATE(134)] = 1321,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(128),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(126),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(127),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(131),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_expression, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant_expression, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_expression, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comparison_expression, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_statement, 5, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_struct_field_repeat1, 2, 0, 0),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_field_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_statement, 5, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_expression, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_definition_repeat1, 2, 0, 0),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_definition, 6, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_union_definition, 6, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_definition, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_package_definition, 3, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_definition, 5, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_union_definition, 5, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comparison_expression, 5, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 9, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 9, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 8, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 5, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_definition, 5, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 1),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_statement, 5, 0, 0),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_statement, 5, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 6, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_definition, 6, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 4, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [266] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
